services:
  user-service:
    build: .
    environment:
      SPRING_APPLICATION_NAME: user-service
      SERVER_PORT: 7001
      SPRING_DATASOURCE_URL: jdbc:mysql://databaseuser:3306/your_database_name?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: your_username
      SPRING_DATASOURCE_PASSWORD: your_password
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
    ports:
      - "7001:7001"
    depends_on:
      - databaseuser
    networks:
        - app-network

  databaseuser:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: your_database_name
      MYSQL_USER: your_username
      MYSQL_PASSWORD: your_password
      MYSQL_ROOT_PASSWORD: your_root_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data_user:/var/lib/mysql
    networks:
      - app-network

volumes:
  mysql_data_user:

networks:
  app-network:
    driver: bridge